services:
  web:
    build: .
    containerName": "Final_Project for_Programming_Class
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      - ENV=development
  
  frontend:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    command: npm run dev -- --host 0.0.0.0