services:
  web:
    build:
      context: .
      target: dev
    ports:
      - "5000:5000"
    volumes:
      - .:/code
      - /opt/venv
    working_dir: /code
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
    depends_on:
      - db
    stdin_open: true
    tty: true
    entrypoint: /bin/bash

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/code
    working_dir: /code
    command: npm run dev -- --host 0.0.0.0
